

KEEP_ALIVE = [
    '-o', "ServerAliveInterval=60",
    '-o', "TCPKeepAlive=true"
]


SSH_VNCVIEWER_OPTIONS = {
   "CheckHostIP": "no",
   "TCPKeepAlive": 30,
   "IdentityFile": "id_rsa",
   "LocalForward":  "auto",
   "RemoteForward": 5901
}

# https://linux.die.net/man/5/ssh_config
# SSH_OPTIONS = {
#    "AddKeysToAgent" : {"required" : False, "default" : None},
#    "AddressFamily" : {"required" : False, "default" : None},
#    "BatchMode" : {"required" : False, "default" : None},
#    "BindAddress" : {"required" : False, "default" : None},
#    "CanonicalDomains" : {"required" : False, "default" : None},
#    "CanonicalizeFallbackLocal" : {"required" : False, "default" : None},
#    "CanonicalizeHostname" : {"required" : False, "default" : None},
#    "CanonicalizeMaxDots" : {"required" : False, "default" : None},
#    "CanonicalizePermittedCNAMEs" : {"required" : False, "default" : None},
#    "CertificateFile" : {"required" : False, "default" : None},
#    "ChallengeResponseAuthentication" : {"required" : False, "default" : None},
#    "CheckHostIP" : {"required" : False, "default" : "no"},
#    "Ciphers" : {"required" : False, "default" : None},
#    "ClearAllForwardings" : {"required" : False, "default" : None},
#    "Compression" : {"required" : False, "default" : None},
#    "ConnectionAttempts" : {"required" : False, "default" : None},
#    "ConnectTimeout" : {"required" : False, "default" : None},
#    "ControlMaster" : {"required" : False, "default" : None},
#    "ControlPath" : {"required" : False, "default" : None},
#    "ControlPersist" : {"required" : False, "default" : None},
#    "DynamicForward" : {"required" : False, "default" : None},
#    "EscapeChar" : {"required" : False, "default" : None},
#    "ExitOnForwardFailure" : {"required" : False, "default" : None},
#    "FingerprintHash" : {"required" : False, "default" : None},
#    "ForwardAgent" : {"required" : False, "default" : None},
#    "ForwardX11" : {"required" : False, "default" : None},
#    "ForwardX11Timeout" : {"required" : False, "default" : None},
#    "ForwardX11Trusted" : {"required" : False, "default" : None},
#    "GatewayPorts" : {"required" : False, "default" : None},
#    "GlobalKnownHostsFile" : {"required" : False, "default" : None},
#    "GSSAPIAuthentication" : {"required" : False, "default" : None},
#    "GSSAPIDelegateCredentials" : {"required" : False, "default" : None},
#    "HashKnownHosts" : {"required" : False, "default" : None},
#    "Host" : {"required" : False, "default" : None},
#    "HostbasedAuthentication" : {"required" : False, "default" : None},
#    "HostbasedKeyTypes" : {"required" : False, "default" : None},
#    "HostKeyAlgorithms" : {"required" : False, "default" : None},
#    "HostKeyAlias" : {"required" : False, "default" : None},
#    "HostName" : {"required" : True, "default" : None},
#    "IdentitiesOnly" : {"required" : False, "default" : None},
#    "IdentityAgent" : {"required" : False, "default" : None},
#    "IdentityFile" : {"required" : True, "default" : None},
#    "Include" : {"required" : False, "default" : None},
#    "IPQoS" : {"required" : False, "default" : None},
#    "KbdInteractiveAuthentication" : {"required" : False, "default" : None},
#    "KbdInteractiveDevices" : {"required" : False, "default" : None},
#    "KexAlgorithms" : {"required" : False, "default" : None},
#    "LocalCommand" : {"required" : False, "default" : None},
#    "LocalForward" : {"required" : False, "default" : None},
#    "LogLevel" : {"required" : False, "default" : None},
#    "MACs" : {"required" : False, "default" : None},
#    "Match" : {"required" : False, "default" : None},
#    "NoHostAuthenticationForLocalhost" : {"required" : False, "default" : None},
#    "NumberOfPasswordPrompts" : {"required" : False, "default" : None},
#    "PasswordAuthentication" : {"required" : False, "default" : None},
#    "PermitLocalCommand" : {"required" : False, "default" : None},
#    "PKCS11Provider" : {"required" : False, "default" : None},
#    "Port" : {"required" : False, "default" : None},
#    "PreferredAuthentications" : {"required" : False, "default" : None},
#    "ProxyCommand" : {"required" : False, "default" : None},
#    "ProxyJump" : {"required" : False, "default" : None},
#    "ProxyUseFdpass" : {"required" : False, "default" : None},
#    "PubkeyAcceptedKeyTypes" : {"required" : False, "default" : None},
#    "PubkeyAuthentication" : {"required" : False, "default" : None},
#    "RekeyLimit" : {"required" : False, "default" : None},
#    "RemoteCommand" : {"required" : False, "default" : None},
#    "RemoteForward" : {"required" : False, "default" : None},
#    "RequestTTY" : {"required" : False, "default" : None},
#    "SendEnv" : {"required" : False, "default" : None},
#    "ServerAliveInterval" : {"required" : False, "default" : None},
#    "ServerAliveCountMax" : {"required" : False, "default" : None},
#    "StreamLocalBindMask" : {"required" : False, "default" : None},
#    "StreamLocalBindUnlink" : {"required" : False, "default" : None},
#    "StrictHostKeyChecking" : {"required" : False, "default" : None},
#    "TCPKeepAlive" : {"required" : False, "default" : None},
#    "Tunnel" : {"required" : False, "default" : None},
#    "TunnelDevice" : {"required" : False, "default" : None},
#    "UpdateHostKeys" : {"required" : False, "default" : None},
#    "UsePrivilegedPort" : {"required" : False, "default" : None},
#    "User" : {"required" : False, "default" : None},
#    "UserKnownHostsFile" : {"required" : False, "default" : None},
#    "VerifyHostKeyDNS" : {"required" : False, "default" : None},
#    "VisualHostKey" : {"required" : False, "default" : None},
#    "XAuthLocation" : {"required" : False, "default" : None}
# }
